name: Build image and deploy to server
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build -t ghcr.io/buraito-kun/dev-assignment:latest .
          docker push ghcr.io/buraito-kun/dev-assignment:latest
  deployment:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Run docker compose file
        run: |
          docker-compose up -d
